/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include "stm32f051xx.h"
#include "stm32f051xx_gpio_driver.h"

void delay1(void)
{
	for (uint32_t i = 0; i < 500000; i++);
}

int main(void)
{
	/*GPIO_Handle_t GpioLedBlue;
	GpioLedBlue.pGPIOx = GPIOC;
	GpioLedBlue.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_8;
	GpioLedBlue.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GpioLedBlue.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;
	GpioLedBlue.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioLedBlue.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;*/


	GPIO_Handle_t GpioLedGreen;
	memset(&GpioLedGreen, 0, sizeof(GpioLedGreen));

	GpioLedGreen.pGPIOx = GPIOC;
	GpioLedGreen.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_9;
	GpioLedGreen.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GpioLedGreen.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;
	GpioLedGreen.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioLedGreen.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_Handle_t GpioBtn;
	memset(&GpioBtn, 0, sizeof(GpioBtn));

	GpioBtn.pGPIOx = GPIOC;
	GpioBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_15;
	GpioBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_FT;
	GpioBtn.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;
	GpioBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PU;

	GPIO_PeriClockControl(GPIOC, ENABLE);
	GPIO_Init(&GpioBtn);
	GPIO_Init(&GpioLedGreen);

	// IRQ config
	GPIO_IRQPriorityConfig(IRQ_EXTI4_15, NVIC_IRQ_PR15);
	GPIO_IRQInterruptCongif(IRQ_EXTI4_15, ENABLE);

	/*while (1) {
		if (GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_0) == ENABLE) {
			GPIO_WriteToOutputPin(GPIOC, GPIO_PIN_9, 1);
		} else {
			GPIO_WriteToOutputPin(GPIOC, GPIO_PIN_9, 0);
		}
	}*/

	while(1) {}
}

void EXTI4_15_IRQHandler(void)
{
	delay1();
	GPIO_IRQHandling(GPIO_PIN_15);
	GPIO_ToggleOutputPin(GPIOC, GPIO_PIN_9);
}



